### ISSUE TITLE
Out of memory with zero-sized files

### ISSUE THREAD

**Issue by lauhub** [olalonde/csv2array#1]
This module crashes when trying to load an empty string from a file and to use csv parsing with it.

Adding a test if(strData.length == 0) return (arrData); before run the parsing corrects the problem.

**Comment by olalonde** [comment]
Could you do a pull request with your fix please?

**Comment by lauhub** [comment]
Sorry, but I don't know how to open a Pull Request.
I don't see any "new pull request" button anywhere in the "Pull requests" section. Do I miss something ?

**Comment by dandv** [comment]
@lauhub: https://help.github.com/articles/using-pull-requests
