### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by tkellen** [olalonde/csv2array#3]
given a file with the contents

```
"r1c1", "r1c2"
"r2c1", "r2c2"
```

csv2array produces:

```
[ [ 'r1c1', ' ' ],
  [ 'r2c1', ' ' ],
  [ '' ] ]
```

**Comment by tkellen** [comment]
This is on node v0.10.26, btw.

**Comment by olalonde** [comment]
Weird, maybe I should have tested a little bit. Looking into it...

**Comment by olalonde** [comment]
Should be fixed now.. update to latest version.

**Comment by tkellen** [comment]
Not quite there yet:

```
"r1c1", "r1c2"
"r2c1", "r2c2"
```

Produces:

```
[ [ 'r1c1', ' "r1c2"' ],
  [ 'r2c1', ' "r2c2"' ] ]
```

**Comment by olalonde** [comment]
I've tried parsing your csv with a couple of parsers and they all seem to not handle it properly because of the spaces... What code produced that CSV? Are you sure it is valid?

**Comment by olalonde** [comment]
According to https://code.google.com/p/jquery-csv/issues/detail?id=21

"According to the CSV spec, whitespace contained outside of a proper delimiter is considered illegal."

**Comment by tkellen** [comment]
I wrote it by hand for a test case on [rechoir](http://github.com/tkellen/node-rechoir) (for eventual use within grunt, gulp etc via [liftoff](http://github.com/tkellen/node-liftoff)). You're correct, this is an invalid CSV format.  We're all good here!

**Comment by tkellen** [comment]
ps: thanks!

**Comment by olalonde** [comment]
Ok, by the way, I've added a skipwhitespace option which seems to work for your csv data but I haven't tested it much.

`csv2array(str, { skipwhitespace: true });`
